/* Generated by: ParserGeneratorCC: Do not edit this line. ParserTreeConstants.java Version 1.1.4 */
package bsh;

public interface ParserTreeConstants {
    public int JJTVOID = 0;
    public int JJTCLASSDECLARATION = 1;
    public int JJTENUMCONSTANT = 2;
    public int JJTBLOCK = 3;
    public int JJTMETHODDECLARATION = 4;
    public int JJTPACKAGEDECLARATION = 5;
    public int JJTIMPORTDECLARATION = 6;
    public int JJTVARIABLEDECLARATOR = 7;
    public int JJTARRAYINITIALIZER = 8;
    public int JJTFORMALPARAMETERS = 9;
    public int JJTFORMALPARAMETER = 10;
    public int JJTTYPE = 11;
    public int JJTRETURNTYPE = 12;
    public int JJTPRIMITIVETYPE = 13;
    public int JJTAMBIGUOUSNAME = 14;
    public int JJTASSIGNMENT = 15;
    public int JJTTERNARYEXPRESSION = 16;
    public int JJTBINARYEXPRESSION = 17;
    public int JJTUNARYEXPRESSION = 18;
    public int JJTCASTEXPRESSION = 19;
    public int JJTPRIMARYEXPRESSION = 20;
    public int JJTMETHODINVOCATION = 21;
    public int JJTLAMBDAEXPRESSION = 22;
    public int JJTPRIMARYSUFFIX = 23;
    public int JJTLITERAL = 24;
    public int JJTARGUMENTS = 25;
    public int JJTALLOCATIONEXPRESSION = 26;
    public int JJTARRAYDIMENSIONS = 27;
    public int JJTLABELEDSTATEMENT = 28;
    public int JJTFORMALCOMMENT = 29;
    public int JJTSWITCHSTATEMENT = 30;
    public int JJTSWITCHLABEL = 31;
    public int JJTIFSTATEMENT = 32;
    public int JJTWHILESTATEMENT = 33;
    public int JJTFORSTATEMENT = 34;
    public int JJTENHANCEDFORSTATEMENT = 35;
    public int JJTTYPEDVARIABLEDECLARATION = 36;
    public int JJTSTATEMENTEXPRESSIONLIST = 37;
    public int JJTRETURNSTATEMENT = 38;
    public int JJTTHROWSTATEMENT = 39;
    public int JJTTRYSTATEMENT = 40;
    public int JJTMULTICATCH = 41;
    public int JJTTRYWITHRESOURCES = 42;
    public int JJTAUTOCLOSEABLE = 43;


    public String[] jjtNodeName = {
            "void",
            "ClassDeclaration",
            "EnumConstant",
            "Block",
            "MethodDeclaration",
            "PackageDeclaration",
            "ImportDeclaration",
            "VariableDeclarator",
            "ArrayInitializer",
            "FormalParameters",
            "FormalParameter",
            "Type",
            "ReturnType",
            "PrimitiveType",
            "AmbiguousName",
            "Assignment",
            "TernaryExpression",
            "BinaryExpression",
            "UnaryExpression",
            "CastExpression",
            "PrimaryExpression",
            "MethodInvocation",
            "LambdaExpression",
            "PrimarySuffix",
            "Literal",
            "Arguments",
            "AllocationExpression",
            "ArrayDimensions",
            "LabeledStatement",
            "FormalComment",
            "SwitchStatement",
            "SwitchLabel",
            "IfStatement",
            "WhileStatement",
            "ForStatement",
            "EnhancedForStatement",
            "TypedVariableDeclaration",
            "StatementExpressionList",
            "ReturnStatement",
            "ThrowStatement",
            "TryStatement",
            "MultiCatch",
            "TryWithResources",
            "AutoCloseable",
    };
}
/* ParserGeneratorCC - OriginalChecksum=e2e2a2ee54f0559e388d8e14d47ae7d3 (do not edit this line) */
